server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      mvc:
        routes:
          - id: eureka-client-1
            uri: http://localhost:8081
            predicates:
              - Path=/client1/**
            filters:
              - StripPrefix=1
          - id: eureka-client-2
            uri: http://localhost:8082
            predicates:
              - Path=/client2/**
            filters:
              - StripPrefix=1