server:
  port: 8081

spring:
  application:
    name: spring-data-jpa-h2
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false"
  jpa:
    show-sql: true
    defer-datasource-initialization: true # Without this script in data.sql won't execute
    hibernate:
      ddl-auto: "update" # This creates / updates tables

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka