server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: spring-boot-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: spring-data-h2
            uri: http://localhost:8081
            predicates:
              - Path=/h2/**
            filters:
              - StripPrefix=1
          - id: spring-data-jpa
            uri: http://localhost:8082
            predicates:
              - Path=/jpa/**
            filters:
              - StripPrefix=1
          - id: spring-security
            uri: http://localhost:8083
            predicates:
              - Path=/security/**
            filters:
              - StripPrefix=1
