spring:
  application:
    name: spring-security
  datasource:
    url: "jdbc:mysql://localhost:3306/test_organization"
    username: "service_account"
    password: "service_account123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "none"